[package]
name = "cddl-cat"
description = "Parse CDDL and validate serialized data"
keywords = ["cddl", "cbor"]
categories = ["encoding", "network-programming", "parser-implementations"]
version = "0.1.0"
repository = "https://github.com/ericseppanen/cddl-cat"
license = "MIT"
authors = ["Eric Seppanen <eds@reric.net>"]
readme = "README.md"
edition = "2018"

[dependencies]
float-ord = "0.2"
serde_cbor = "0.11"
serde = "1.0"
# nom's default-features are ["std", "lexical"].
nom = { version = "5.1.1", features = ["std"], default-features = false }
hex = "0.4"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
