name: Build and Test

on:
  push:
    branches: [ master, ci_testing ]
  pull_request:
    branches: [ master ]

jobs:
  cargo-build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cargo build
      run: cargo build
    - name: cargo test
      run: cargo test

